### ISSUE TITLE
Timekeeper breaks Jasmine 1.14.5 when used with nodejs v0.10.25

### ISSUE THREAD

**Issue by VanTanev** [vesln/timekeeper#10]
Updating to nodejs v0.10.30 fixes the problem.

The broken test had the shape of:

```
it('tests something that has a callback', function(done) {
  timekeeper.freeze(moment("some date in the past").toDate())

  Model.doSomethingWithCallback(function(err, result) {
    tk.reset();
    expect(result).toBe('proper result');
    done();
  });
})
```

This test just hanged jasmine with nodejs v0.10.25. Jasmine's test timeout never triggered, and the next test was never executed.

Verified to work with v0.10.30 and v0.12.4.

**Comment by VanTanev** [comment]
Just a note, v0.10.25 is the default version that comes with Ubuntu :)

**Comment by freewil** [comment]
The hanging issue was probably due to the hackish `sleep()` function that was used in some of the tests. This was removed in v0.1.0, commit 4e4641ccc414e06bfff8268c844b832e28f9153d

**Comment by VanTanev** [comment]
Thanks for getting back to this. I don't have a current project to test
this, but I hope it works well.

Have a good one :)
