### ISSUE TITLE
TypeError: Cannot read property 'UTC' of undefined

### ISSUE THREAD

**Issue by noahsw** [vesln/timekeeper#20]
I got this while trying to use this package in a Meteor 1.3 project.

```
TypeError: Cannot read property 'UTC' of undefined
W20160821-22:58:59.447(-7)? (STDERR)     at node_modules/timekeeper/lib/timekeeper.js:103:1
W20160821-22:58:59.448(-7)? (STDERR)     at NativeDate (node_modules/timekeeper/lib/timekeeper.js:9:1)
W20160821-22:58:59.449(-7)? (STDERR)     at meteorInstall.node_modules.timekeeper.lib.timekeeper.js (node_modules/timekeeper/lib/timekeeper.js:18:1)
```

**Comment by freewil** [comment]
Could you provide any example code to re-produce this issue? Or even better: add a test case that showcases the bug?

**Comment by thebarty** [comment]
Hah, funny thing! Same thing over here with a meteor 1.4 project.

I have tried to get timekeeper into my tests by doing something like this:
```
/* eslint-env mocha */
/* eslint-disable func-names, prefer-arrow-callback */
import { Meteor } from 'meteor/meteor'

// ANY of those fail
const { timekeeper } = require('timekeeper')
const timekeeper = require('timekeeper')
import { timekeeper } from 'timekeeper'

if (Meteor.isServer) {
  describe('SyncedCron', () => {
    beforeEach(function (done) {
      // Mock Time
      timekeeper.reset()
    })

    // COLLECTION EXISTS
    it('works correctly', () => {
    })
  })
}
```

@noahsw Have you found a solution or alternative that works with meteor?

**Comment by Lucasosf** [comment]
Same with me, any function of the timekeeper fails. =/

**Comment by Lucasosf** [comment]
btw, I'm using it with Meteor too.

**Comment by LinusU** [comment]
This seems to be a problem with Meteor.

If someone could give me a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) I'd be happy to reopen...
