### ISSUE TITLE
1.0?

### ISSUE THREAD

**Issue by chadxz** [vesln/timekeeper#21]
Anything preventing a 1.0 release? This project has existed for quite a while and i've been using it to test certain things for years. The api seems stable, so why not release 1.0?

**Comment by vesln** [comment]
not really... I'm looking for extra maintainers since the people I've added seem fairly inactive sadly... since you've been using it for quite some time, do you want me to add you as a collaborator and npm owner so you can release/maintain when you can?

**Comment by LinusU** [comment]
I've been inactive since there haven't been that much to do...

I think that a 1.0 release sounds good 👍

**Comment by vesln** [comment]
ah, @LinusU apologies, you proved me wrong immediately :)

**Comment by LinusU** [comment]
no problems at all 👌 

Version 1.0 is now published 🙌

**Comment by freewil** [comment]
> I've been inactive since there haven't been that much to do...

Haha, same. I watch the repo for issues that come up, but yeah, not much to do.

v1.0 👍
