### ISSUE TITLE
when i npm i timekeeper package , npm remove my other 4 package

### ISSUE THREAD

**Issue by NextZeus** [vesln/timekeeper#25]
I wonder why , when i install timekeeper package , npm auto remove my local other 4 package. 

```
async-listener
emitter-listener
shimmer
tingyun

```

**Comment by LinusU** [comment]
I think that you should open this bug with npm instead, we don't have any dependencies or `postinstall` scripts so I don't see how this could be caused by timekeeper...

Good luck!
