### ISSUE TITLE
Time Travel froze the UI

### ISSUE THREAD

**Issue by heuism** [vesln/timekeeper#28]
Hi @vesln, I tried this one on an app testing for react native. I tried on iOS and it is working fine. However, when I applied it for Android, it just froze after I travel through time, I can click or anything, until I remove the app from background and the start the app again. I am unsure what is the reason? If you can help me with this that would be really great. thanks

**Comment by LinusU** [comment]
If this is still an issue in the latest version of React Native I'd be happy to reopen...
