### ISSUE TITLE
timekeeper.freeze() without params causes wrong behaviour

### ISSUE THREAD

**Issue by valyakin** [vesln/timekeeper#41]
Hello,

Currently, this code causes wrong behavior because timekeeper.freeze() not designed to work without arguments.

```javascript
const tk = require('timekeeper')
tk.freeze()

console.log(Date.now()) // NaN

```

I've added the PR to fix this issue: https://github.com/vesln/timekeeper/pull/40
Feel free to consider to merge it

**Comment by LinusU** [comment]
Fixed in 2.3.0
