### ISSUE TITLE
No warning message about the project status

### ISSUE THREAD

**Issue by masonlouchart** [vesln/timekeeper#44]
Hello there 👋 ,

I was about to use this library in my tests but one of my colleagues warned me about the project's status. After double checking, I noticed that one [PR opened in 2020](https://github.com/vesln/timekeeper/pull/40) (3 years ago), [solving one of the issues](https://github.com/vesln/timekeeper/issues/41), has not been reviewed yet. My conclusion is this project is not maintained anymore.

Would it be possible to have some warning at the top of the README file?

Thank you for providing such an amazing and useful library to the community 🙏 

PS: I ended to use [jest.useFakeTimers](https://jestjs.io/docs/jest-object#jestusefaketimersfaketimersconfig). 
PS2: _"The TypeScript examples from this [Jest official documentation] page will only work as documented if you explicitly import Jest APIs"_

**Comment by LinusU** [comment]
I had just missed the PR, there is not much changes because the api is stable and it's a small library...

**Comment by masonlouchart** [comment]
Thank you for confirming 🙏
